### ISSUE TITLE
README improvement ideas

### ISSUE THREAD

**Issue by valscion** [TylorS/reginn#1]
Hi there!

I saw this project thanks [to your tweet being retweeted by Gleb Bahmutov](https://twitter.com/TylorS167/status/778809680936132608). It's really exciting and I'm looking forward to using it if I need to make a CLI in the future!

I really liked the documentation flow in README.md, great work there!

However, when continuing to the API Documentation part, I struggled with understanding how `desc` can be used. I almost stopped reading there, but then figured that hey, maybe I could help a bit and offer some improvements to the documentation while I still haven't tested out the code!
- I'd like to avoid phrases such as `A Description is just what you'd expect.` — I really don't know what I'd expect (does it describe the entire application? A command? Or something entirely else?) so it was a bit off-putting to not understand immediately what it was about.
- I don't really know what `a parent type` means in this context usage-wise, and the example didn't help me. Maybe the example could be amended to show how it ties into the `Flag` or `Command` types? 
- The `desc()` function isn't used anywhere else but in the API documentation, so even after reading the entire README, I still don't know how it is used.
  - Do you think that maybe expanding the `help()` command section could showcase how `desc` ties into commands?

Also, I feel like the `you guessed it` in the `help()` documentation doesn't really give any meaningful information to a first-time reader. As I didn't have any previous knowledge of this library, I actually first assumed that `help()` would be used as a flag — `node ./myapp.js --help`. So now that I didn't actually guess it correctly, I felt a bit bummed.

But hey! This README is still among one of the best and most concise READMEs I've come across, so all in all you've done awesome work! These are just a few nitpicks that I wanted to share as I got the feeling that you'd appreciate feedback on the README as it is :blush:

Let me know if you think that these concerns are valid. If you tell me how `desc` is actually used in an example CLI, I could try to put up a pull request that tries to resolve these issues I came across :smile:

**Comment by TylorS** [comment]
Hello @valscion! Thank you for taking the time to read the entire README, it's pretty long. And I appreciate even more you taking the time to write up an issue on things you felt were subpar.

I should have known that `desc` and `help` would bring some confusion. They were added at the last minute because I realized users would probably want/expect some sort of automatic help display, as it is common to many alternatives. That being said, they didn't quite get the love as the other aspects of the documentation and now I'm being called out on it, which is good. :smile: 

I definitely put it on my list of things to do.

My current thinking is to sort of expand on the current `desc` example with something like `flag(desc('this is a flag'), ...)`, and also choosing words a little more carefully with a little less assumption. Then I think it'd be good to say something like `More example usage here` with a link to the help section.

My thinking is to show the example in the walkthrough section again, but with the help decorator wrapped around it with the addition of `desc()` in the example text. How does that sound?

Thanks again for this, issues are invaluable for open-source maintainers. :+1:

**Comment by TylorS** [comment]
@valscion I've update the README and removed the assumptive text that was in there. I added a slightly more useful example for the `desc` section, but also added a much more useful example to `help`

**Comment by valscion** [comment]
Awesome! Glad I could be of help. I'm right now heading home for the night, I'll try to remember to give more details tomorrow when I get on my laptop but overall you've done great improvements! And now I pretty much understand how `desc()` works, hooray! 😄

**Comment by TylorS** [comment]
Great, more feedback always welcomed.

**Comment by valscion** [comment]
For more great context on writing friendly documentation that can be understood easily, I highly suggest reading https://github.com/thejameskyle/documentation-handbook — it's super awesome!

**Comment by TylorS** [comment]
Thanks for the tip!
